package com.healthscore.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class ConsumoAguaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumoAguaAllPropertiesEquals(ConsumoAgua expected, ConsumoAgua actual) {
        assertConsumoAguaAutoGeneratedPropertiesEquals(expected, actual);
        assertConsumoAguaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumoAguaAllUpdatablePropertiesEquals(ConsumoAgua expected, ConsumoAgua actual) {
        assertConsumoAguaUpdatableFieldsEquals(expected, actual);
        assertConsumoAguaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumoAguaAutoGeneratedPropertiesEquals(ConsumoAgua expected, ConsumoAgua actual) {
        assertThat(expected)
            .as("Verify ConsumoAgua auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumoAguaUpdatableFieldsEquals(ConsumoAgua expected, ConsumoAgua actual) {
        assertThat(expected)
            .as("Verify ConsumoAgua relevant properties")
            .satisfies(e -> assertThat(e.getDataConsumo()).as("check dataConsumo").isEqualTo(actual.getDataConsumo()))
            .satisfies(e -> assertThat(e.getQuantidadeMl()).as("check quantidadeMl").isEqualTo(actual.getQuantidadeMl()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertConsumoAguaUpdatableRelationshipsEquals(ConsumoAgua expected, ConsumoAgua actual) {}
}
