package com.healthscore.app.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class QualidadeSonoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualidadeSonoAllPropertiesEquals(QualidadeSono expected, QualidadeSono actual) {
        assertQualidadeSonoAutoGeneratedPropertiesEquals(expected, actual);
        assertQualidadeSonoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualidadeSonoAllUpdatablePropertiesEquals(QualidadeSono expected, QualidadeSono actual) {
        assertQualidadeSonoUpdatableFieldsEquals(expected, actual);
        assertQualidadeSonoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualidadeSonoAutoGeneratedPropertiesEquals(QualidadeSono expected, QualidadeSono actual) {
        assertThat(expected)
            .as("Verify QualidadeSono auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualidadeSonoUpdatableFieldsEquals(QualidadeSono expected, QualidadeSono actual) {
        assertThat(expected)
            .as("Verify QualidadeSono relevant properties")
            .satisfies(e -> assertThat(e.getData()).as("check data").isEqualTo(actual.getData()))
            .satisfies(e -> assertThat(e.getHorasSono()).as("check horasSono").isEqualTo(actual.getHorasSono()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertQualidadeSonoUpdatableRelationshipsEquals(QualidadeSono expected, QualidadeSono actual) {}
}
